name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: quay.io
      - name: Build and run VMaaS
        run: docker-compose up --build -d
      - name: Wait for VMaaS to run
        run: |
          set +e
          resp=1
          while [ "$resp" -ne 0 ]; do 
            curl http://localhost:8080/api/v1/monitoring/health
            resp=$?
          done
      - name: Sync VMaaS repolist
        run: |
          echo "${{ secrets.REPOLIST_JSON }}" > repolist.json
          ./scripts/setup_db repolist.json
      - name: Integration tests
        run: |
          docker run -it --name iqe --rm --network host \
            -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings ${{ secrets.IQE_TESTS_IMAGE }} \
            iqe tests plugin vulnerability -k 'vmaas'
